### ISSUE TITLE
未来の祝日についてはアルゴリズムベースで決める

### ISSUE THREAD

**Issue by yusuke** [yusuke/japan-holidays#1]
https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html に記載の情報をもとに、csvにない未来の祝日情報を算出する。

**Comment by amay077** [comment]
未来の祝日に関連して、「サポートする日付範囲を返すメソッド」があると良いなと思いました（例: ``1955/01/01 ～ 2021/12/31``）。
現行APIでは、 未来の ``2022/01/01`` が「休日ではない」のか「ライブラリのサポート範囲外である」のか判別できないな、と思いました。

**Comment by yusuke** [comment]
そうですね、アルゴリズムベースで算出された祝日なのか内閣府の確定情報が元になっている祝日なのかは判別する方法が欲しいですね

**Comment by yusuke** [comment]
ひとまずアルゴリズムでも妥当に祝休日を導出できるようになったので、サポート範囲は未来に渡ってだしますよということでいいかな・・？

アルゴリズムベースなのか内閣府の確定情報なのか、判別したいという要件がありそうであれば別途対応で。

**Comment by amay077** [comment]
> アルゴリズムベースなのか内閣府の確定情報なのか、判別したいという要件

未来の計画を立てるときに「この祝日は確定されたものか？」が欲しい場面はありそうですが、そうですね、発生したら別 issue が良いと思います。
ありがとうございます。
